#!/bin/sh

set -eu

cd $(dirname "$0")

VERSION=0.1

PREFIX="/usr/local"
MANPREFIX="${PREFIX}/share/man"

if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 127
fi

pli_tools() {
	if [ "$#" -eq 0 ]; then
		exit 1;
	fi

	echo "Installing $1"
	cp -f "tools/$1" "${PREFIX}/bin"
	cp -f "tools/$1.1" "${MANPREFIX}/man1"
	chmod +x "${PREFIX}/bin/$1"
	echo "Success"
}

tools() {
	mkdir -p "${PREFIX}/bin"
	mkdir -p "${MANPREFIX}/man1"

	pli_tools mkdesk	
	pli_tools miplay	

	echo "Finished installing tools"
}

all() {
	tools
	echo "Finished installing all"
}

if [ "$1" == "--help" ] || [ "$1" == "" ]; then
	echo "Install options:"
	echo "  --help"
	echo "  tools"
	echo "  all"
	echo "  pli_tools"
	echo
	echo "Beware that install [COMMAND] will result in the execution of [COMMAND]"
	exit 1
fi

$1

cd - 
