#!/bin/sh

# (C) Copyright 2023 Muhammad Faran Aiki
# Installation of my shell scripts

set -eu

cd $(dirname "$0")

VERSION=0.1

if [ "$EUID" -ne 0 ] || ! [ -n "${SUDO_USER+x}" ]; then
	echo "Please run as root"
	exit 127
fi


if [ -z "${INSTALL+x}" ]; then
	INSTALL=""
fi

USER="${INSTALL}/home/${SUDO_USER}"
PREFIX="${INSTALL}/usr/local"
MANPREFIX="${PREFIX}/share/man"

pli_tools() {
	if [ "$#" -eq 0 ]; then
		exit 1;
	fi

	echo "Installing $1"
	cp -f "tools/$1" "${PREFIX}/bin"
	cp -f "tools/$1.1" "${MANPREFIX}/man1"
	chmod +x "${PREFIX}/bin/$1"
	echo "Success"
}

# TODO use this
cp_adv() {
	if [ "$#" -le 2 ]; then
		exit 1;
	fi

	if ! $[ "$()" = "/" ]; then
		mkdir -p "$2"
		cp -r "$1" "$2"
	else
		mkdir -p $(dirname "$2")
		cp -r "$1" "$2"
	fi
}

tools() {
	mkdir -p "${PREFIX}/bin"
	mkdir -p "${MANPREFIX}/man1"

	pli_tools mkdesk	
	pli_tools miplay	

	echo "Finished installing tools"
}

config() {
	echo "Are you really sure you want to install config? (it will override your current config) [y/N]"
	read -p "> " ans

	if [ "$ans" != "y" ];
	then
		return
	fi

	echo "Configuring .bashrc"
	cp -f "config/.bashrc" "${USER}"

	echo "Configuring .zshrc"
	cp -f "config/.zshrc" "${USER}"

	echo "Configuring vim/nvim"
	mkdir -p "${USER}/.config/nvim/"
	cp -f "config/vim/.vimrc" "${USER}/.vimrc"
	cp -f "config/vim/.vimrc" "${USER}/.config/nvim/init.vim"
	mkdir -p "${USER}/.vim/"
	cp -rf "config/vim/templates" "${USER}/.vim/" 
	cp -rf "config/vim/fshort" "${USER}/.vim/" 

	echo "Finished installing config"
}

all() {
	config
	tools
	echo "Finished installing all"
}

if [ "$#" -eq 0 ]; then
	all
	exit 0
fi

if [ "$1" == "--help" ]; then
	echo "Install options:"
	echo "  --help"
	echo "  all"
	echo "  tools"
	echo "  config"
	echo "  pli_tools"
	echo
	echo "Beware that install [COMMAND] will result in the execution of [COMMAND]"
	exit 1
fi

$1

cd - 
