#!/bin/bash

# UNTESTED! TODO TEST

# (C) Copyright 2022 Muhammad Faran Aiki
# No right reserved

# This script offers no warranty
# This script offers bloated softwares

# Can be executed in ./install_arch

# Do not use this file without precautions or knowledges
# This setup is for Arch Linux distribution that uses SystemD
# This script assumes that you have sudo installed

set -eu

# Checking installation

# Checking
echo "Are you sure you want to download? [y/N]"
read -p ans

if [ "$ans" != "y" ]; then
	echo Aborted
	exit 1
fi

# First alias
alias yay="yay --removemake --cleanafter --norebuild"
alias pacman="pacman --noconfirm"

# Setting variables
__pacstrap_to=''

# Check programs needed
if ! [ -f /usr/bin/sudo ]
then
	printf "Error: No 'sudo' installed."
	
	printf "Checking if the terminal is already on root."
	if [ ~ = "/root" ]
	then 
		printf "The terminal is already on root."
		printf "Aliasing 'sudo' into ''."
		alias sudo=''
	else
		printf "The terminal is not on root; aborting."
		printf "Try 'su && ./faran-arch.sh' to run on root."
		exit1
	fi
	
fi

if ! [ -f /usr/bin/pacman ]
then
	printf "Error: No 'pacman' installed, checking pacstrap."
	
	if  [ -f /usr/bin/pacstrap ]
	then
		printf "Pacstrap exists, in which/what directory do you want the script to install?"
		read __pacstrap_to
		
		while ! [ -d $__pacstrap_to ]
		do
			printf "Try again, that directory does not exists."
			read __pacstrap_to
		done
		
		printf "Packages now will be installed in '$__pacstrap_to'."
		printf "Aliasing 'pacman' to 'pacstrap'."
		
		alias pacman='pacstrap --noconfirm'
	else
		exit
	fi
fi


# Do not assume safety
sudo chown root /

# Install linux
sudo pacman -S base base-devel linux linux-firmware 

# Config
# ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

# Install installers
sudo pacman -S git wget curl pacman-contrib

# Install text editors
sudo pacman -S vim-gui-common vim vi visudo sed grep awk

# Change the PacMan config
sudo sed "s/#[multilib]/[multilib]/mg" $__pacstrap_to/etc/pacman.conf
sudo sed "s/#Include = \/etc\/pacman.d\/mirrorlist/Include = \/etc\/pacman.d\/mirrorlist/mg" $__pacstrap_to/etc/pacman.conf
printf "File '/etc/pacman.conf' has been modified."

# Install advanced installers
pushd

# Check if home directory exists, root or not
if [ -f ~ ]
then
	mkdir ~/Downloads 2> /dev/null 
	cd ~/Downloads
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
else
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
fi

popd

# Install file systems
sudo pacman -S ntfs-3g

# Install basics
sudo pacman -S xorg iwd

# Install drivers
sudo pacman -S alsa pulseaudio pavucontrol jack jack2-dbus bluez bluez-libs bluez-utils bluez-qt hplip
yay -S CUPS
printf "Download the drivers for printer yourself."

# Install advanced drivers
yay -S b43-firmware

# Downloading environment resources

# Setting environment resources

# Making things easier
sudo cp $__pacstrap_to/etc/pacman.d/mirrorlist $__pacstrap_to/etc/pacman.d/mirrorlist.backup
sudo awk '/^## Country Name$/{f=1; next}f==0{next}/^$/{exit}{print substr($0, 1);}' $__pacstrap_to/etc/pacman.d/mirrorlist.backup
sudo sed -i 's/^#Server/Server/' $__pacstrap_to/etc/pacman.d/mirrorlist.backup
sudo rankmirrors -n 6 $__pacstrap_to/etc/pacman.d/mirrorlist.backup > $__pacstrap_to/etc/pacman.d/mirrorlist

# Install applications
sudo pacman -S krita lmms # Install "real" LMMS on your own

# Install WINE Is wiNdows Emulator
sudo pacman -S wine wine-staging
sudo pacman -S $(pactree -l wine) $(pactree -l wine-staging)

# Install programming language
sudo pacman julia ghc cabal python

# Install side applications
sudo pacman thunar kitty

# Install xf86 videos
sudo pacman -S xf86-video-amdgpu xf86-video-ati xf86-video-intel xf86-video-vesa

# Install fonts
sudo pacman -S noto-fonts-cjk ttf-carlito ttf-dejavu ttf-hack

# Install advanced fonts
yay -S ttf-ubuntu-font-family ttf-ms-fonts ttf-inconsolata

# Install utilities
sudo pacman -S htop radeontop btop

# Install internet utilities
sudo pacman -S openvpn net-tools pacman wireless_tools gnu-netcat nmap mtr

# Install browsers
yay -S firefox chromium brave

# Install virtual machineys
pacman -S qemu virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat libguestfs virtualbox

# Setting WINE
winetricks settings fontsmooth=rgb

# Download 'hacking' tools
sudo pacman -S metasploit

# Download network tools
yay -S aircrack-ng

# "Remove" heat from laptop
sudo pacman -S thermald cpupower cpupower-gui

# Remove conflicting SystemD units
sudo airmon-ng check kill

# Controller supports
sudo pacman -S linuxconsole
yay -S xboxdrv

# Systemd configuration
sudo systemctl enable iwd thermald cups libvirtd
sudo systemctl start iwd thermald libvirtd --now

# Modprobing
modprobe uinput vboxdrv

# Setup Vim
yay -S aur/vundle-git 

# Setup LaTeX
sudo pacman -S texlive-formatsextra texlive-latexextra

# Setup touch screen
sudo pacman -S xf86-input-evdev xf86-input-libinput xf86-input-elographics

# Setup zsh and shell
sudo pacman -S zsh dash
yay -S zsh-autocomplete zsh-autosuggestions zsh-syntax-highlighting

# Setup for Audio Workstation
pacman -S dexed zynaddsubfx surge
yay -S vital

# Setup others
timedatectl

# Rebooting
printf "Script finishes.\n"
printf "You can either reboot or do what you want.\n"
